version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo "installing something"
      - npm install
  pre_build:
    commands:
      - echo "we are in the pre build phase"
  build:
    commands:
      - echo "we are in the build block"
      - echo "we will run some tests"
      - npm run test
  post_build:
    commands:
      - echo "we are in the post build phase"
